# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.13.0]
    steps:
      - uses: actions/checkout@v2
      - name: Using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls -asl
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.1.0
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Upload to server
        uses: shimataro/ssh-key-action@v2.1.0
      - run: rsync -r ./client ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.CLIENT_PATH }}
#    - run: npm ci
#    - run: # NODE_ENV=production npm run build-storybook
#    - run: NODE_ENV=production npm run build
#      env:
# NEXT_PUBLIC_WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
# NEXT_PUBLIC_WORDPRESS_PREVIEW_SECRET: ${{ secrets.WORDPRESS_PREVIEW_SECRET }}
# NEXT_PUBLIC_WORDPRESS_AUTH_REFRESH_TOKEN: ${{ secrets.WORDPRESS_AUTH_REFRESH_TOKEN }}
#    - name: upload
#      run: cd ../ && rsync -r ./client ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.CLIENT_PATH }}
